### ISSUE TITLE
When the text encoding is changed from the menu, the application crashes.

### ISSUE THREAD

**Issue by setanarut** [HexFiend/HexFiend#452] opened 2023-11-27 16:39 UTC
When the text encoding is changed from the menu, the application suddenly closes and crashes.

![Ekran Resmi 2023-11-27 19 28 49](https://github.com/HexFiend/HexFiend/assets/36481442/bbac70b8-d1cf-4a48-83c2-a4ce0d7c0c91)

## Info

- macOS Monterey 12.7.1 (21G920) - MacBook Pro 2016 (Intel)
- Hex Fiend Version 2.17 (1700842191)

Crash log:

[Hexfiend_crash_report.txt](https://github.com/HexFiend/HexFiend/files/13477828/Hexfiend_crash_report.txt)

**Comment by kainjow** [comment] 2023-11-27 20:45
Thanks. Dupe of https://github.com/HexFiend/HexFiend/issues/450 - I’ll try to get a new build out soon. For now you can workaround by selecting Customize first.

**Closed by kainjow** 2023-11-27 20:45 UTC
