### ISSUE TITLE
Highlight color for "other" view

### ISSUE THREAD

**Issue by HarrisonMc555** [HexFiend/HexFiend#442] opened 2023-09-27 17:12 UTC
If you highlight a sequence of bytes, it is highlighted using the system's "Accent Color". In addition, the corresponding text is also highlighted. However, this highlighting is always a lighter gray, which is extremely subtle when the system is in "Dark Mode". This also applies in reverse (highlighting the text will highlight the corresponding binary in light gray).

Could we add an option to change the "other view highlighting color"?

Normally this is where I'd offer to contribute, but I have zero experience with Objective-C, so it would probably take me too long to get up and running just for a (relatively) small change.

For now, I'm just switching my system to "Light Mode" when I'm constantly going back and forth between Binary and Text, and turning it back to "Dark Mode" when I'm done :smile:

**Comment by kainjow** [comment] 2023-10-02 05:04
I believe this is a dupe of #309

**Closed by kainjow** 2023-10-02 05:04 UTC
Labels: Feature

**Comment by HarrisonMc555** [comment] 2023-10-02 16:21
Thanks for the quick response!
